FROM node:10-slim

USER node

RUN mkdir -p /home/node/temp_cashe

RUN mkdir -p /home/node/app

WORKDIR /home/node/temp_cashe

ARG NPM_AUTH_TOKEN

COPY --chown=node .npmrc ./
COPY --chown=node package.json ./
COPY --chown=node package-lock.json ./
COPY --chown=node ./docker/local/entrypoint.sh ./

RUN npm ci

WORKDIR /home/node/app
